name: tome
on:
  push:
    -branch:
      -develop
  pull_request:
    -branch:
      -develop
jobes:
  build:
    runs-on: ubuntu-lastes
    seps:
      - name: welcome step
        run: echo "welcome to github"
      -name: Clone Repo
        uses: actions/checkout@v4
      -name: Repo Info
       run: |
        echo "Here is the informaction of Repo"
        echo "Repo Name: :${{github.repository}}"
        echo "Event Name: :${{github.event_name}}"
        git branch testing
        git branch
        git log
        git -v
        igt config --local --list  
